export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED'
export const INCREMENT = 'counter/INCREMENT'
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED'
export const DECREMENT = 'counter/DECREMENT'

export const FETCH_ACTIVE_APPLICATIONS = 'map/FETCH_ACTIVE_APPLICATIONS'
export const RECEIVE_ACTIVE_APPLICATIONS = 'map/RECEIVE_ACTIVE_APPLICATIONS'
